// 用常量定义 mutation 的类型 （ vuex 文档建议这样做 ）
const SET_SINGER = 'SET_SINGER'

const SET_DISC = 'SET_DISC'

const SET_PLAYING_STATE = 'SET_PLAYING_STATE'

const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

const SET_PLAY_LIST = 'SET_PLAY_LIST'

const SET_SEQUENCE_LIST = 'SET_SEQUENCE_LIST'

const SET_MODE = 'SET_MODE'

const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export {
  SET_SINGER,
  SET_DISC,
  SET_PLAYING_STATE,
  SET_FULL_SCREEN,
  SET_PLAY_LIST,
  SET_SEQUENCE_LIST,
  SET_MODE,
  SET_CURRENT_INDEX
}
